name: dart_basic_math_lib
description: Simple dart math library for lcg, rational numbers and trig functions.
author: gfleet.games <studentdavidli@gmail.com>
homepage: https://github.com/FriendlyUser/dart-simple-math
version: 0.1.4
environment:
  sdk: '>=2.2.0 <3.0.0'

dev_dependencies:
  test: ^1.9.2