name: dart_lcg
description: Simple dart Project to Illustrate how to publish a dart package.
author: gfleet.games <studentdavidli@gmail.com>
homepage: https://github.com
version: 0.1.2
environment:
  sdk: '>=2.2.0 <3.0.0'

dev_dependencies:
  test: ^1.9.2